import Challenge.Bls12381G2Add.Reference.Proofs.SourceFp2InvImagReadback

open Challenge.Bls12381G2Add.Reference.Proofs.SourceSemantics

#check fp2InvAfterRealStores_loadWord_before_out
#check fp2InvAfterRealStores_c1
#check fp2InvAfterRealStores_scalar
#check fp2InvNeg_eq
#check fp2InvImagScalar_eq
#check fp2InvImag_eq
