import Challenge.Bls12381G2Add.Reference.Proofs.SourceInputCodec

set_option warningAsError true

open Challenge.Bls12381G2Add.Reference.Proofs.SourceSemantics

#check decodeFp_eq_none_iff_sourceField
#check decodeFp2_eq_none_iff_sourceFp2
