import Challenge.Bls12381G2Add.Reference.Proofs.SourceMainSecondInfinity

open Challenge.Bls12381G2Add.Reference.Proofs.SourceSemantics

#check step_mainSecondInfinity_return
#check step_mainSecondInfinity_continue
