import Challenge.Bls12381G2Add.Reference.Proofs.SourceFp2InvLowFinal

open Challenge.Bls12381G2Add.Reference.Proofs.SourceSemantics

#check fp2InvFinalState_loadWord_before_scratch
#check fp2InvFinalState_fp2At_before_scratch
