import Challenge.Bls12381G2Add.Reference.Proofs.SourceMainFiniteExceptionalLawful

set_option warningAsError true

open Challenge.Bls12381G2Add.Reference.Proofs.SourceSemantics

#check clearPointState_readBytes_zero
#check encodeG2_infinity_toList
#check mainFiniteClear_returned_codec
#check mainFiniteOpposite_affineInfinity
#check mainFiniteZeroY_affineInfinity
