import Challenge.Bls12381G2Add.Reference.Proofs.SourceFp2MulRefinement
set_option warningAsError true
open Challenge.Bls12381G2Add.Reference.Proofs.SourceSemantics
#check fp2MulV0_eq_mulCanonical
#check fp2MulV1_eq_mulCanonical
#check fp2MulReal_eq_subSource
#check fp2MulSumA_eq_addSource
#check fp2MulSumB_eq_addSource
#check fp2MulCross_eq_mulCanonical
#check fp2MulVSum_eq_addSource
#check fp2MulImag_eq_subSource
