import Challenge.Bls12381G2Add.Reference.Proofs.SourceMainFinitePredicates

set_option warningAsError true

open Challenge.Bls12381G2Add.Reference.Proofs.SourceSemantics

#check fp2EqValue_ne_zero_iff_lawful
#check fp2ZeroValue_ne_zero_iff_lawful
#check mainFiniteXEq1_ne_zero_iff
#check mainFiniteXEq2_ne_zero_iff
#check mainDoubleYEq_ne_zero_iff
#check mainDoubleYZero_ne_zero_iff
#check mainDoubleXEq2_ne_zero_iff
