import Challenge.Bls12381G2Add.Reference.Proofs.SourceFpMulMemory

#check Challenge.Bls12381G2Add.Reference.Proofs.SourceSemantics.fpMulFinalState_readBytes_after_scratch
#check Challenge.Bls12381G2Add.Reference.Proofs.SourceSemantics.fpMulFinalState_loadWord_after_scratch
