import Challenge.Bls12381G1Msm.Reference.Proofs.SourcePointAddUnequalDeltaBridge
set_option warningAsError true
open Challenge.Bls12381G1Msm.Reference.Proofs.SourceSemantics
#check step_pointAddUnequalDeltaInitAndStmt
#print axioms step_pointAddUnequalDeltaInitAndStmt
