import Challenge.Bls12381G2Add.Reference.Proofs.SourceFp2InvRefinement

open Challenge.Bls12381G2Add.Reference.Proofs.SourceSemantics

#check fp2InvSquare0_eq_mulCanonical
#check fp2InvSquare1_eq_mulCanonical
#check fp2InvNorm_eq_addSource
#check fp2InvScalar_eq_invCanonical
#check fp2InvReal_eq_mulCanonical
#check fp2InvNeg_eq_subSourceZero
#check fp2InvImag_eq_mulCanonical
